version: '3'
services:

  hub:
    image: selenium/hub
    ports:
      - "4444:4444" 

  chromenode:
    image: selenium/node-chrome
    ports:
      - "5555:5555"
    links:
      - hub  
    privileged: true  
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

  seleniumtests:
    image: maven:3.5-jdk-8-alpine
    volumes:
      - ./:/usr/src/mvn-src
    working_dir: /usr/src/mvn-src
    command: ./wait-for-it.sh hub:4444 -- mvn clean test
    expose:
      - 5005
    ports:
      - "5005:5005"  
    links:
      - hub
      - chromenode
